### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by miguelramos** [TanStack/vue-query#8]
** Improvements
- Integrate vue eslint plugin
- Put testing/eslint working to integrate PR and maintain consistency
- Exclude current core from eslint and tests

**Comment by Shyrro** [comment]
@miguelramos Since PR related to the subject have been merged, we should close this issue. I tried but i can't link PR's to this

**Comment by miguelramos** [comment]
@Shyrro of course yes. I close it.
